### ISSUE TITLE
mariadb grants not working

### ISSUE THREAD

**Issue by mrenvoize** [digibib/kohadevbox#113]
If using MariaDB, the grants are not performed by the playbook correctly, so one has to manually add them before running the web installer.

**Comment by tomascohen** [comment]
I belive this is a koha-create issue. I'm trying to tackle it down.

**Comment by joubu** [comment]
Will be fixed by bug 17513 - koha-create does not set GRANTS correctly
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=17513
