### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mrenvoize** [digibib/kohadevbox#114]
We could really do with the options in /var/user.yml documenting better.

We could do with documenting the git aliases that are automatically added.

**Comment by tomascohen** [comment]
I'd say we lack lots of documentation, specifically how to do things inside the kohadevbox, as it is a gitified koha, and is quite different from a regular dev setup. Can someone write a list of things to do?

**Comment by tomascohen** [comment]
I hope i didn't miss any aliases.

**Comment by mrenvoize** [comment]
Thanks for this, really appreciated. 

I'm going to spend some time in the train today documenting the git aliases I've discovered the past few days and submit a pull request
