### ISSUE TITLE
OPAC and staff sessions are shared

### ISSUE THREAD

**Issue by joubu** [digibib/kohadevbox#121]
Since we are using ports to separate OPAC and staff interfaces, the sessions are shared.
It's a bit frustrating when you need to use different users to test something.

That could be fixed using different server names in the apache config, like staff.kohadev.vm and opac.kohadev.vm
We just need to make port, prefix and suffix customisable.

**Comment by tomascohen** [comment]
This will help. We might also need to add documentation for users to add those domains to their hosts file.
