### ISSUE TITLE
Add DB dump/restore functionality

### ISSUE THREAD

**Issue by boutros** [digibib/kohadevbox#14]
This would be handy when testing patches which changes the database.

Could for example be provided as to shell functions:
dump_db()   # dumps the database to /tmp/somefile.db
restore_db() # restore the database from /tmp/somefile.db

Or as tasks in a Makefile?

**Comment by wizzyrea** [comment]
I think you can do this from within the devbox by issuing a 

sudo koha-dump kohadev - the db will be dumped to /var/spool/koha/kohadev

you can then restore it with
sudo koha-restore /var/spool/koha/kohadev/kohadev-<date>.sql.gz

**Comment by tomascohen** [comment]
@wizzyrea: Can u confirm those commands work? We could document it on the README.md file, PRs accepted :-D
