### ISSUE TITLE
Include lessc

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#140]
Otherwise compiling the .less files becomes difficult.

**Comment by mtompset** [comment]
https://nodejs.org/en/download/package-manager/ -- that got it done nicely. :)

**Comment by mtompset** [comment]
-- or not. Still unclear on how to get it to work.

**Comment by tomascohen** [comment]
Done, @mtompset. Please check everything is ok.

**Comment by mtompset** [comment]
Sorry for the slow feedback. Just tried everything under the manually part. Looks good.
https://wiki.koha-community.org/wiki/Working_with_Bootstrap_OPAC_LESS_files
