### ISSUE TITLE
error: vagrant up with bento/debian-8.4-i386

### ISSUE THREAD

**Issue by clkirby1** [digibib/kohadevbox#143]
Task [kohadevbox: Update Apt cache and system packages] 
"...failed E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.'
to retry use: --limit @/home/ckirby/kohadevbox/site.retry"

Development environment has worked previously.

**Comment by tomascohen** [comment]
You need to fix the broken package install situation. This doesn't seem to be kohadevbox-related, though.
It can be just that you interrupted the box creation and are trying to resume it, or just that the bento box is not functional out of the box.

You should *vagrant destroy* and start over.

Side note: Why 8.4? There's the bento/debian-8.6-i386 box already.
