### ISSUE TITLE
On Windows, synced_folder type defaults to rsync

### ISSUE THREAD

**Issue by oleonard** [digibib/kohadevbox#144]
Working on Windows 7, "vagrant up" kept giving me an error:
'"rsync" could not be found on your PATH'

Vagrantfile appears to be correctly setting config.vm.synced_folder type to "virtualbox," but the value Vagrant appears to be using is from a different location.

Prompted by https://stackoverflow.com/questions/34176041/vagrant-with-virtualbox-on-windows10-rsync-could-not-be-found-on-your-path#34882657 I modified this file:

C:\Users\{user}\.vagrant.d\boxes\debian-VAGRANTSLASH-jessie64\8.6.1\virtualbox\include\_Vagrantfile

...to change config.vm.synced_folder "type" to "virtualbox"

Only then did the "up" process proceed without the error. Why wouldn't Vagrant be honoring the setting defined in Vagrantfile?

**Comment by tomascohen** [comment]
@mtompset can we have your aid here please?

**Comment by karamqubsi** [comment]
for the first time it worked with me on windows 10  👍  . and that after doing the suggested fix 
"to change config.vm.synced_folder "type" to "virtualbox""

**Comment by mtompset** [comment]
karamqubsi is correct, I believe.
I have been using:
$ git diff origin/master
diff --git a/Vagrantfile b/Vagrantfile
index 9e0e294..616a3fa 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -35,6 +35,9 @@ Vagrant.configure(2) do |config|
   end

   config.vm.hostname = "kohadevbox"
+  if OS.windows?
+    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
+  end

   config.vm.define "jessie", primary: true do |jessie|
     jessie.vm.box = "debian/jessie64"

**Comment by tomascohen** [comment]
This is already fixed my @mtompset pull request #154
