### ISSUE TITLE
xenial lacks openjdk-7-jre

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#146]
TASK [kohadevbox : Elasticsearch 1.7 | Add Elasticsearch dependencies] *********
failed: [xenial] (item=[u'openjdk-7-jre']) => {"failed": true, "item": ["openjdk-7-jre"], "msg": "No package matching 'openjdk-7-jre' is available"}

**Comment by mtompset** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/_installation.html
Higher can be used, it seems.

**Comment by tomascohen** [comment]
@mtompset we are moving fast towards ES 2.4 / ES 5.1. It might not be worth this. And also, I'd prefer that we added an exeption for xenial as we do in other places. In the lines of:

`
  - name: Elasticsearch 1.7 | Add Elasticsearch dependencies
    apt: pkg={{ item }} state=latest
    with_items:
      - openjdk-7-jre
    when:
      - ansible_distribution_release != 'xenial'
  - name: Elasticsearch 1.7 | Add Elasticsearch dependencies
    apt: pkg={{ item }} state=latest
    with_items:
      - openjdk-8-jre
    when:
      - ansible_distribution_release == 'xenial'
`
