### ISSUE TITLE
vagrant up xenial setup koha fails with Internal Server Error

### ISSUE THREAD

**Issue by lazarosfs** [digibib/kohadevbox#148]
Dear all,

I wish you all Happy New Year and whatever your heart desires.
I have been trying to make kohadevbox run for weeks now dealing with all sorts of problems being unable to finish he installation correctly.
Most issiues seem resolved today and after running git checkout and vagrant destroy and vagrant xenial up the installation seems to finish succesfully.
However the vagrant vm box has 2 ip's 192.168.50.1, 10.0.2.15.
I am only able to connect to both on :8080 port and try to run setup using default options (marc21) and get a "Internal Server Error" at the end.
Can anyone point me on some directions on how to locate the error and proceed?
Best Regards,

lazarosfs

**Comment by lazarosfs** [comment]
The problem appears at tha last step of the web setup when chosen to install basic initial configuration settings.
To reproduce just get into http://192.168.50.1:8080 and follow the steps.
Any help?

**Comment by tomascohen** [comment]
This looks like a Koha issue, probably a fixed one.
