### ISSUE TITLE
Reprovisioning?

### ISSUE THREAD

**Issue by boutros** [digibib/kohadevbox#15]
Should it be possibe to reprovision? Right now you have to nuke the box and build it again I think, as the shell provisioner doesn't handle allready existing directories, installed packages and so on.

I guess this is only necessary if the provisioning steps changes often. Hopefully it will be fairly stable, but now during development it would be nice to be able to just run any new steps introduced in the provisioning.

**Comment by tomascohen** [comment]
I'd like to mark this one as 'fixed' as you can run the following command in current master to accomplish the task:

`vagrant provision`
