### ISSUE TITLE
Can running vagrant up with SYNC_REPO and then --provision overwrite local git repo?

### ISSUE THREAD

**Issue by regionbibliotekhalland** [digibib/kohadevbox#155]
Had a local git repo on my machine I wanted to bring into a new kohadevbox. It hung during installation and I reran vagrant up with --provision. It finished just fine, but it cloned the actual koha-community repo this time and when I checked my local git repo again origin and upstream was now different. I guess this might happen because the devbox mirrors to the host what it does to the repo and when cloning it overwrote my config. But if this can be verified maybe there should be a slight warning not to sync anything that you only have a local copy of. (I don't mind since this was a throw away testing repo and branch anyhow)

**Comment by tomascohen** [comment]
if kohadevbox is up with SYNC_REPO set, and then you reprovision without SYNC_REPO, it will probably overwrite it. That's why we always suggest to have SYNC_REPO set on the environment (i.e. exported in your .bash_profile or .bashrc file)
