### ISSUE TITLE
Test::DBIx::Class install fails because of ...PopulateMore because of DBD::SQLite

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#166]
diff --git a/roles/kohadevbox/tasks/qatools.yml b/roles/kohadevbox/tasks/qatools.yml
index 8b35743..fa5fd3b 100644
--- a/roles/kohadevbox/tasks/qatools.yml
+++ b/roles/kohadevbox/tasks/qatools.yml
@@ -26,6 +26,7 @@
   become_user: root
   cpanm: name={{ item }} mirror={{ cpan_mirror }}
   with_items:
+    - DBD::SQLite
     - HTTPD::Bench::ApacheBench
     - Test::DBIx::Class
   retries: 5

This works. :)

**Comment by tomascohen** [comment]
@mtompset thanks for the fix.
