### ISSUE TITLE
Why NFS?

### ISSUE THREAD

**Issue by boutros** [digibib/kohadevbox#167]
Just wondering, any particular reason for using NFS - is it because it works on MACs/Windows?

I'm using Linux, so vagrant's default syncing method (vboxsf I belive) is working perfect. I see no reason to run an NFS server on my machine.

It's not a problem at all, I just disable NFS manually. Just curious!

**Comment by tomascohen** [comment]
I moved to NFS once the official Debian images removed the 'Extension pack' which provides the 'vboxfs' filesystem. I haven't tracked the status of it.

When I worked on making it easier for Windows users (i.e. running ansible inside the box and having alternate mount methods for Windows) I discovered this plugin that automatically installs the 'Extension pack' and could be used on the UNIX hosts too.

The reason I didn't invest time on it was the lack of time and the feeling that 'vboxfs'  was too slow compared to NFS, and even SSHFS. We can give it a try if you want to, maybe adding some switch through ENV. Not a priority for me but open to ideas.

**Comment by boutros** [comment]
> We can give it a try if you want to, maybe adding some switch through ENV. Not a priority for me but open to ideas.

Nah, don't bother. As long as NFS is working fine for all OSes I think it's good to keep it :)

Thanks for the explanation!
