### ISSUE TITLE
dev_install broken in koha-functions.sh

### ISSUE THREAD

**Issue by ohait** [digibib/kohadevbox#168]
adjust_paths_dev_install() fails because it can't find <dev_install> in koha-conf.xml foir instance kohadev

this cause a cascade of errors, the harder to find is koha-upgrade-schema fails silently, causing postinstall script of koha-common.dpkg to fail without any helpful error message

the incriminating line is:
dev_install=$(xmlstarlet sel -t -v 'yazgfs/config/dev_install' /etc/koha/sites/$instancename/koha-conf.xml)

by using yazgfs/config/intranetdir it works, but i suspect a better aproach is to add <dev_install> to koha-conf.xml

**Comment by tomascohen** [comment]
Hi, this got fixed by #163 by including it automatically. Update your kohadevbox dir by running 

`$ git pull`

You need to destroy an recreate your box. Otherwise, just add _<dev_install>/home/vagrant/kohaclone</dev_install>_ to your koha-conf.xml.

Regards

**Comment by ohait** [comment]
oh ok, splendid.
