### ISSUE TITLE
'vagrant up' always fails unexpectedly, if SYNC_REPO is unset

### ISSUE THREAD

**Issue by KohaAloha** [digibib/kohadevbox#175]
to recreate error...

$ unset SYNC_REPO
$ vagrant destroy
$ vagrant up
...
[kohadevbox : Replace koha-* scripts]
fatal: [jessie]: FAILED! => {"changed": true, "cmd": "perl /home/vagrant/misc4dev/cp_debian_files.pl", "delta": "0:00:00.067425", "end": "2017-03-09 00:11:24.709122", "failed": true, "rc": 2, "start": "2017-03-09 00:11:24.641697", "stderr": "Cannnot open file No such file or directory at /home/vagrant/misc4dev/cp_debian_files.pl line 24.", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by linuxes** [comment]
What the smeg is going on? 
It also trying to access /home/vagrant/.. when env SYNC_REPO is set,.. 
I tried export also, even when i made dir at /home/vagrant with chmod, it didnt helped too

![obrazek](https://cloud.githubusercontent.com/assets/1339083/23877832/8fdca9fa-0844-11e7-983c-c44b3638d13f.png)

**Comment by tomascohen** [comment]
This one is a duplicate for #173 , which is already fixed! Thanks for reporting!
