### ISSUE TITLE
Koha QA tools | CPAN dependencies failed because CPAN mirror was down

### ISSUE THREAD

**Issue by bartonski** [digibib/kohadevbox#178]
During provisioning, I'm getting the error below. This is caused by the fact that http://mirror.cc.columbia.edu/ was down.

    TASK [kohadevbox : Koha QA tools | CPAN dependencies] **************************
    changed: [jessie] => (item=DBD::SQLite)
    changed: [jessie] => (item=HTTPD::Bench::ApacheBench)
    failed: [jessie] (item=Test::DBIx::Class) => {"cmd": "/usr/bin/cpanm Test::DBIx::Class --mirror http://mirror.cc.columbia.edu/pub/software/cpan", "failed": true, "item": "Test::DBIx::Class", "msg": "! Download http://mirror.cc.columbia.edu/pub/software/cpan/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz failed. Retrying ... \n! Download http://mirror.cc.columbia.edu/pub/software/cpan/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz failed. Retrying ... \n! Download http://mirror.cc.columbia.edu/pub/software/cpan/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz failed. Retrying ... \n! Failed to download http://mirror.cc.columbia.edu/pub/software/cpan/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz\n! Failed to fetch distribution Test-Output-1.031\n! Installing the dependencies failed: Module 'Test::Output' is not installed\n! Bailing out the installation for Data-Perl-0.002009.\n! Installing the dependencies failed: Module 'Data::Perl'is not installed\n! Bailing out the installation for MooX-HandlesVia-0.001008.\n! Installing the dependencies failed: Module 'MooX::HandlesVia' is not installed\n! Bailing out the installation for DBIx-Class-Schema-PopulateMore-0.19.\n! Installing the dependencies failed: Module 'DBIx::Class::Schema::PopulateMore' is not installed\n! Bailing out the installation for Test-DBIx-Class-0.52.\n"}

Maybe we could choose mirrors based on geographical location and mirror status, as found in   http://mirrors.cpan.org/cpan-json.txt ?

**Comment by bartonski** [comment]
Upon further inspection, I found that it wasn't the mirror itself that was down, it's simply that

http://mirror.cc.columbia.edu/pub/software/cpan/authors/id/B/BD/BDFOY/Test-Output-1.031.tar.gz

Doesn't exist.

I was able to get around this by un-commenting `cpan_mirror` in `vars/user.yml` and changing the value to

    cpan_mirror: http://cpan.metacpan.org/

As such, I think that this isn't an issue with kohadevbox itself... it might be worth putting a note in the documentation about this.

**Comment by oleonard** [comment]
I'd say it is a kohadevbox issue unless there is a really good reason to specify a single mirror? Is there?

**Comment by tomascohen** [comment]
I'd say we should change it to either Barton's suggestion or make it configurable.

This mirror got hardcoded a while back when everyone was having issues installing Test::DBIx::Class and the problems where dependencies in mirrors....

Please send a pull request and I can push it.

**Comment by tomascohen** [comment]
I switched it to barton's suggestion. If there's consensus, we could leave it undefined by default too, and let cpanm pick the right mirror. But I need to remind you that this was introduced due to the mirror's recurrent inconsistency.
