### ISSUE TITLE
Part of vagrant up fails installing qa-tools if running behind a firewall no https option

### ISSUE THREAD

**Issue by ldjamison** [digibib/kohadevbox#195]
For all other git clone options located in user.yml there is an option to override downloading as https over git except for qa-tools which causes a non-fatal failure during `vagrant up` if running behind a firewall which blocks git protocol requests.

user.yml contains (on line 71) a git protocol URL even though the default (at least from my observation) _is_ the git protocol so it appears to be the only GitHub URL without a https option.

I file this for the sake of completeness in the user.yml.

**Comment by tomascohen** [comment]
I agree we could switch all git repos to HTTP(S) and it would have a good impact for users behind a firewall, with no harm.

**Comment by tomascohen** [comment]
The community repositories you mention don't offer an HTTPS interface. Maybe this should be better requested to repository administrators, then we could fix it.

**Comment by tomascohen** [comment]
@ldjamison I'm closing this one. You should request the community repo to be available through HTTPS in community's Bugzilla. If you get a positive response, then open a new request here.
