### ISSUE TITLE
Vagrant up throwing fatal errors on Windows 8.1

### ISSUE THREAD

**Issue by ldjamison** [digibib/kohadevbox#199]
Tried spinning up a box on Windows 8.1 Pro (64-bit) but hit fatal errors that I've been unable to remedy.

    TASK [kohadevbox : Instance creation | Check for instance existence] ***********
    fatal: [jessie]: FAILED! => {"changed": false, "cmd": "koha-list '|' grep kohadev", "failed": true, "msg": "
    [Errno 2] No such file or directory", "rc": 2}
    ...ignoring

    TASK [kohadevbox : Instance creation | Create Koha instance] *******************
    fatal: [jessie]: FAILED! => {"failed": true, "msg": "The conditional check 'result.stdout == \"\"' failed. The 
    error was: error while evaluating conditional (result.stdout == \"\"): 'dict object' has no attribute 
    'stdout'\n\nThe error appears to have been in '/vagrant/roles/kohadevbox/tasks/koha-instance.yml': 
    line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe 
    offending line appears to be:\n\n\n- name: Instance creation | Create Koha instance\n  ^ here\n"}

    RUNNING HANDLER [kohadevbox : restart apache] **********************************

    RUNNING HANDLER [kohadevbox : reload ssh] **************************************
        to retry, use: --limit @/vagrant/site.retry

    PLAY RECAP *********************************************************************
    jessie                     : ok=28   changed=6    unreachable=0    failed=1

    Ansible failed to complete successfully. Any error output should be
    visible above. Please fix these errors and try again.

**Comment by ldjamison** [comment]
Contents of user.yml:

```
# Default configuration values
---

vagrant_home_dir: /home/vagrant

# ssh_key_from_host: false

# Uncomment and set sync_repo to true to avoid cloning the koha.
# repository Normally this should be done automatically if you use the
# environment variable.
sync_repo: true
skip_webinstaller: true
create_admin_user: true
enable_memcached: true
#elasticsearch: true
#elasticsearch_version: '5.x'
plack: true

# Set mysql_engine: mysql | mariadb
# mysql_engine: mysql
# Set to "*" to listen on all interfaces
# mysql_bind_address: "127.0.0.1"

koha_official_repo_origin: debian.koha-community.org
koha_official_repo: http://{{ koha_official_repo_origin }}/koha
koha_official_repo_key: http://debian.koha-community.org/koha/gpg.asc
koha_official_repo_distribution: unstable

# koha_custom_repo_origin: apt.abunchofthings.net
# koha_custom_repo: '[trusted=yes] https://{{ koha_custom_repo_origin }}/koha-nightly'
# koha_custom_repo_has_key: no
# koha_custom_repo_key:
# koha_custom_repo_distribution: unstable

# koha_use_custom_repo: yes
# koha_pin_custom_repo: no

koha_git_repo: http://git.koha-community.org/koha.git
koha_git_branch: master

# koha_instance_name: kohadev
# koha_domain: .myDNSname.org
# koha_intra_port: 8080
# koha_intra_prefix: ""
# koha_intra_suffix: "-intra"
# koha_opac_port: 80
# koha_opac_prefix: ""
# koha_opac_suffix: ""
# koha_marc_flavour: marc21
# koha_zebra_language: en
# koha_db_password: password
# koha_admin_user: admin
# koha_admin_pass: admin

gitify_repo: https://github.com/mkfifo/koha-gitify.git
gitify_version: master
gitify_dir: /home/vagrant/gitify

gitbz_repo: https://github.com/joubu/git-bz.git
gitbz_version: apply_on_cascade
gitbz_dir: /home/vagrant/gitbz

# release_tools_repo: git://git.koha-community.org/release-tools.git
# release_tools_version: master
# release_tools_dir: /home/vagrant/release-tools

misc4dev_repo: https://github.com/joubu/koha-misc4dev.git
misc4dev_version: master
misc4dev_dir: /home/vagrant/misc4dev

koha_qa_repo: git://git.koha-community.org/qa-test-tools.git
koha_qa_version: master
koha_qa_dir: /home/vagrant/qa-test-tools

node_version: node_6.x

git_email: [redacted]
git_full_name: [redacted]

bz_user: [redacted]
bz_password: [redacted]

cpan_mirror: http://cpan.metacpan.org

# extra_tools:
#  - vim
#  - byobu
#  - htop

# editor: vim

```

**Comment by mtompset** [comment]
Was this immediate after a vagrant destroy and then vagrant up or a vagrant up for the first time? Or was this a vagrant provision after the first time failing? Because tiny pieces left behind make provisioning a pain if you had a failed provision previously.

**Comment by ldjamison** [comment]
@mtompset so I've been testing it and it appears to only happen  with SYNC_REPO enabled on Windows 8.1 and misc_4_dev commented out.

All I do is run
`export SYNC_REPO="c:\\Users\\Lee\\kohaclone\\"`
then run `vagrant up` and this error happens.

**Comment by ldjamison** [comment]
Full ansible-playbook output
`PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [jessie]

TASK [Update apt cache if needed] **********************************************
changed: [jessie]

TASK [kohadevbox : Tools | Install default tools] ******************************
changed: [jessie] => (item=[u'apt-transport-https', u'bash-completion', u'cpanminus', u'dh-make-perl', u'git', u'git-email', u'apache2', u'libapache2-mpm-itk', u'libdata-printer-perl', u'perltidy', u'pmtools', u'memcached'])

TASK [kohadevbox : Tools | Install extra tools] ********************************
changed: [jessie]

TASK [kohadevbox : Tools | Stop memcached if required] *************************
ok: [jessie]

TASK [kohadevbox : Environment | SSH tweak] ************************************
changed: [jessie]

TASK [kohadevbox : Environment | Set git user configuration] *******************
changed: [jessie]

TASK [kohadevbox : Environment | Set Bash configuration] ***********************
changed: [jessie]

TASK [kohadevbox : Environment | Set some Bash aliases] ************************
changed: [jessie]

TASK [kohadevbox : Environment | Set up vimrc] *********************************
changed: [jessie]

TASK [kohadevbox : Environment | Copy public ssh key from host to vagrant] *****
skipping: [jessie]

TASK [kohadevbox : Environment | Copy private ssh key from host to vagrant] ****
skipping: [jessie]

TASK [kohadevbox : Apache | MPM fix] *******************************************
ok: [jessie]

TASK [kohadevbox : Apache | Disable default vhost] *****************************
changed: [jessie]

TASK [kohadevbox : Apache | Set ports] *****************************************
changed: [jessie]

TASK [kohadevbox : Apache | Enable needed modules] *****************************
changed: [jessie] => (item=rewrite)
changed: [jessie] => (item=headers)
changed: [jessie] => (item=proxy_http)
changed: [jessie] => (item=cgi)

TASK [kohadevbox : Database | Install (mysql)] *********************************
changed: [jessie]

TASK [kohadevbox : Database | Set up (mysql)] **********************************
ok: [jessie]

TASK [kohadevbox : koha-gitify | Clone koha-gitify] ****************************
changed: [jessie]

TASK [kohadevbox : Koha source | Clone repository] *****************************
skipping: [jessie]

TASK [kohadevbox : Install Koha | Add official Koha repository (key)] **********
changed: [jessie]

TASK [kohadevbox : Install Koha | Add official Koha repository (repo)] *********
changed: [jessie]

TASK [kohadevbox : Install Koha | Add custom Koha repository (key)] ************
skipping: [jessie]

TASK [kohadevbox : Install Koha | Add custom Koha repository (repo)] ***********
changed: [jessie]

TASK [kohadevbox : Install Koha | Pin custom Koha repository (repo)] ***********
skipping: [jessie]

TASK [kohadevbox : Install Koha | Install koha-common] *************************
changed: [jessie]

TASK [kohadevbox : Install Koha | Install older JSON::Validator] ***************
ok: [jessie]

TASK [kohadevbox : misc4dev | Clone the misc4dev repo] *************************
changed: [jessie]

TASK [kohadevbox : Koha packages tweaks | Replace koha-* scripts] **************
changed: [jessie]

TASK [kohadevbox : Koha packages tweaks | Use our koha-sites.conf file] ********
changed: [jessie]

TASK [kohadevbox : Koha packages tweaks | Use our Koha's passwd file] **********
changed: [jessie]

TASK [kohadevbox : Koha packages tweaks | Use our koha-conf-site.xml.in file] ***
changed: [jessie]

TASK [kohadevbox : Instance creation | Check for instance existence] ***********
fatal: [jessie]: FAILED! => {"changed": false, "cmd": "koha-list '|' grep kohadev", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
...ignoring

TASK [kohadevbox : Instance creation | Create Koha instance] *******************
fatal: [jessie]: FAILED! => {"failed": true, "msg": "The conditional check 'result.stdout == \"\"' failed. The error was: error while evaluating conditional (result.stdout == \"\"): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/vagrant/roles/kohadevbox/tasks/koha-instance.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Instance creation | Create Koha instance\n  ^ here\n"}

RUNNING HANDLER [kohadevbox : restart apache] **********************************

RUNNING HANDLER [kohadevbox : reload ssh] **************************************
        to retry, use: --limit @/vagrant/site.retry

PLAY RECAP *********************************************************************
jessie                     : ok=28   changed=22   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`

**Comment by tomascohen** [comment]
@ldjamison this looks like a not-mounted synced repo problem and not KohaDevBox itself. I'm closing it. Feel free to dispute my claim and reopen it.
