### ISSUE TITLE
Use a default repository install of ansible 2.1 or higher when possible.

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#200]
Stretch seems to not like the Ubuntu Repo for ansible. Since the README file says 1.9, I'll hack the ansible install shell script.

**Comment by mtompset** [comment]
See the associated pull request: https://github.com/digibib/kohadevbox/pull/201

**Comment by mtompset** [comment]
This pull request has been tested as described in the test plan (destroy and up for jessie, stretch, and xenial). It's ready for merging now. :)

**Comment by tomascohen** [comment]
@mtompset I've pushed a patch for #203 that solves most of the commits from the original pull request you sent. I'm closing your pull request, and hope you can take the bits needed for Stretch to work and provide a new one!

**Comment by mtompset** [comment]
Okay. Just retested a smaller rework. But this isn't the place to put it.
