### ISSUE TITLE
Integrate kohadocs repository and Sphinx

### ISSUE THREAD

**Issue by kfischer** [digibib/kohadevbox#202]
It would be nice if the kohadocs repository and pythin-sphinx tools necessary to generate the manual locally could be included in the kohadevbox to make it even easier to contribute to the manual.

https://gitlab.com/koha-community-devs-users/kohadocs

You need at least python-sphinx 1.4, I successfully tested the workflow with 1.5.1 yesterday.

**Comment by ldjamison** [comment]
I'm working on integrating kohadocs as we speak!

**Comment by tomascohen** [comment]
This has been implemented on pull request #204
Nice job, @ldjamison! Thanks!
