### ISSUE TITLE
Replace 'tools/install-ansible.sh' with native config

### ISSUE THREAD

**Issue by minusdavid** [digibib/kohadevbox#203]
I was looking through the Vagrant documentation and I found that 'ansible.install_mode = "default"' should do the same thing as "tools/install-ansible.sh" with less hassle. That said, I haven't tried it myself yet.

https://www.vagrantup.com/docs/provisioning/ansible_local.html

**Comment by tomascohen** [comment]
@minusdavid that's an excellent idea. Thanks for mentioning! I'm looking forward for the time you can help us coding!

**Comment by tomascohen** [comment]
Done!
