### ISSUE TITLE
vagrant up stretch fails

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#206]
To reproduce:
vagrant destroy jessie
vagrant destroy xenial
vagrant destroy stretch
vagrant up jessie
vagrant up xenial
vagrant up stretch

Only stretch fails. Any patch provided must produce not only a clean stretch, but clean jessie and xenial 'vagrant up's as well.

**Comment by tomascohen** [comment]
@romper, I recommend that you wait a bit, for the Mojolicious upgrade so you don't bother to change the JSON::Validator package

**Comment by mtompset** [comment]
#207 addresses this.

**Comment by mtompset** [comment]
Revised PR in place.

**Comment by mtompset** [comment]
@tomascohen When is the Mojolicious upgrade? Because right now, this works. Why not fix it now, and fix it later? It's my time to waste. ;)

**Comment by tomascohen** [comment]
Pushed, thanks @mtompset !
