### ISSUE TITLE
Add support for Selenium tests

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#222]
There are currently a number of Koha patches in Bugzilla for adding Selenium tests. Could we set up kohadevbox for easily running these tests?

**Comment by MagnusEnger** [comment]
This describes the steps that need to ba taken, I think: 
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=18974#c8

**Comment by tomascohen** [comment]
@MagnusEnger there you go ;-)

**Comment by MagnusEnger** [comment]
Excellent! Thanks a lot!
