### ISSUE TITLE
reset_all no longer builds a working DB since Koha bug 19724

### ISSUE THREAD

**Issue by greenjimll** [digibib/kohadevbox#240]
Koha bug 19274 added a "timestamp" column to the biblio_metadata table.  If you run a reset_all on kohadevbox the file:

/home/vagrant/misc4dev/data/sql/marc21/1611/after_17196/biblio_metadata.sql

no longer works, because the number of fields it has doesn't match the number of columns in the table. The solution I used was to edit the two INSERT statements in the file to explicitly list the id, biblionumber, format, marcflavour and metadata columns being inserted, and leave the timestamp to be automatically generated.  I don't know if this the "approved" way of sorting the issue, but it seems to work.

**Comment by joubu** [comment]
See http://lists.koha-community.org/pipermail/koha-devel/2017-December/044195.html
koha-misc4dev needs to be updated

**Comment by tomascohen** [comment]
For the record: in this kind of situation, reprovisioning should be enough.
