### ISSUE TITLE
kohadcos typographical error

### ISSUE THREAD

**Issue by mtompset** [digibib/kohadevbox#249]
When trying to get a kohadevbox to run on Ubuntu 16.04 LTS, difficulties ensured, but one was due to vars/defaults.yml (and not really vars/user.yml.sample) having kohadcos instead of kohadocs in the file. This triggered an error about "mkdir -p ''" when trying to provision it for the first time.

**Comment by tomascohen** [comment]
I'm sorry you had trouble with VirtualBox, that's outside the scope of KohaDevBox, tough.
Thanks for the fix!
