### ISSUE TITLE
No way of logging into staff client after running reset_all

### ISSUE THREAD

**Issue by dj-shiz** [digibib/kohadevbox#263]
After running reset_all I find myself unable to login as db users are now prevented from logging into the staff client as of bug 20489 being pushed to master on the 20th of April this year (https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=20489).

As running reset_all does not automatically trigger the onboarding tool when loading the staff client afterwards, this means that there is no superlibrarian account to login with. None of the sample users in the borrowers table have staff client access.

Could the reset_all command be configured to setup a default superlibrarian user or even to trigger the onboarding tool so you could create one at least?

**Comment by tomascohen** [comment]
@dj-shiz kohadevbox creates a superlibrarian user by default, and reset_all recreates it. By default the credentials are _koha_ / _koha_, and this is controlled in the _vars/user.yml_ configuration (see _koha_admin_user_ and _koha_admin_pass_ entries).
