### ISSUE TITLE
Make it possibe to stop and restart Plack

### ISSUE THREAD

**Issue by boutros** [digibib/kohadevbox#31]
Maybe set it up as an upstart service?
Or whatever method Plack/Starman is set up with in production environments.

Plack process is now terminated when you stop the VM (vagrant halt), and has to be started manually when you start up the VM again. I suspect this is because the way plack is started, by backgrounding the plackup.sh script.

**Comment by tomascohen** [comment]
The koha-common package provides now convenient ways to run Plack for the configured instances. Even koha-gitify has been adjusted to this behaviour.
