### ISSUE TITLE
Add a default circulation rule

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#35]
All patron categories, all item types. Without this, there will be surprises when e.g. placing a hold.

**Comment by wizzyrea** [comment]
This is a bug in Koha itself - should fix it there. :)

**Comment by MagnusEnger** [comment]
That is true! I'll see what I can do.

**Comment by MagnusEnger** [comment]
There, I added a Koha bug for it:

Bug 13576 - Add a default circulation rule to the optional sample data
http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=13576
