### ISSUE TITLE
Set DBIC_TRACE=1

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#36]
Not sure how it will behave in the context of Koha, but this is how you make DBIx::Class output/log the queries it generates:

```
export DBIC_TRACE=1
```

Maybe it should be configurable.

**Comment by tomascohen** [comment]
@MagnusEnger maybe we should consider this once a concrete proposal arises. Definitely not worth enabling by default. But this and having a remote debugger are the missing pieces.
