### ISSUE TITLE
Mount error on shared folder for virtualbox 4.3.10 (ubuntu 12.04-14.04)

### ISSUE THREAD

**Issue by bensinober** [digibib/kohadevbox#37]
Stock ubuntu using virtualbox from apt-get may experience problems with vagrant boxes using shared folders (/vagrant). This is a known issue with virtualbox 4.3.10 and may be remedied such:

`sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions`

http://www.binarytides.com/vbox-guest-additions-ubuntu-14-04/

perhaps include in README?

**Comment by tomascohen** [comment]
We don't use guest additions anymore, as support was dropped from the official debian box. We use NFS instead.
