### ISSUE TITLE
Skipping webinstaller gives login error on 3.17

### ISSUE THREAD

**Issue by bensinober** [digibib/kohadevbox#38]
Installing without webinstaller yields the following error: 
`The format you asked for ('') is unrecognized. at /home/vagrant/kohaclone/C4/NewsChannels.pm line 212`
and unable to log in.

Same version with webinstaller works, but it may well be a Koha bug in the News Channels module

**Comment by tomascohen** [comment]
3.18 is no longer maintained,  This is pre-3.18.
