### ISSUE TITLE
Gitify or traditional dev install?

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#46]
Currently, kohadevbox uses a gitified package install, mostly because that was the apporach that was easy to get up and running fast. There are pros and cons to both approaches. This is a good place to collect them.

**Comment by mtompset** [comment]
A full git install will be slower, yes, but it requires less understanding of the development environment. If you know git, and where the koha repository is, off you go. If something breaks, no problem, just restart.

**Comment by tomascohen** [comment]
I think having a proper packages-equivalent environment for developing/testing is an interesting goal too. It happened to me while working on the release management team, that we worked really hard on stuff, but testing it in a packages (and Plack?) environment was not part of the workflow.
So I vote for a gitified one, possibly improving koha-gitify if needed (as we did for the packages' plack.psgi file).

**Comment by tomascohen** [comment]
I'm closing this for now. Maybe later we find better ways to do this.
