### ISSUE TITLE
Document how to run Koha's tests

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#48]
While testing [Bug 13276 - t/XSLT.t shouldn't depend on the DB](http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=13276), I turned off MySQL to make the tests fail, but I was still getting:

```
$ sudo koha-shell -c "prove  t/XSLT.t" kohadev
t/XSLT.t .. ok   
All tests successful.
Files=1, Tests=8,  2 wallclock secs ( 0.02 usr  0.01 sys +  0.48 cusr  0.45 csys =  0.96 CPU)
Result: PASS
```

To test properly, I had to run this:

```
$ sudo -u kohadev-koha KOHA_CONF=/etc/koha/sites/kohadev/koha-conf.xml prove t/XSLT.t
```

This should probably be documented in the README and maybe used in a alias/shell function?

**Comment by tomascohen** [comment]
Good catch. Maybe we can just suggest:
´´´
sudo koha-shell kohadev
cd kohaclone
prove t/<paste your favourite test>
´´´
The new KohaDevBox pastes a .bashrc file on the instance's user, so all needed variables are set to run the tests (even those for running the full stack tests in t/db_dependent/www).

What do you think @MagnusEnger ?

**Comment by MagnusEnger** [comment]
Yeah, that sounds like a way to go. 

I must admit I had forgotten you could to "sudo koha-shell kohadev" to become the kohadev user. I always just use koha-shell with -c.

**Comment by tomascohen** [comment]
Done!
