### ISSUE TITLE
Make MariaDB an option

### ISSUE THREAD

**Issue by MagnusEnger** [digibib/kohadevbox#51]
Make it possible to choose [MariaDB](https://mariadb.org/) before creating a new box. 

This should probably come with a warning that MariaDB + Koha might have some issues. See e.g. [Koha bug 5366](http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=5366).

**Comment by tomascohen** [comment]
Look @joubu

**Comment by tomascohen** [comment]
Done! Check mysql_engine in vars/user.yml.example
