### ISSUE TITLE
New devboxes coming up with marc21 in marcflavour rather than MARC21

### ISSUE THREAD

**Issue by wizzyrea** [digibib/kohadevbox#52]
This seems to cause a problem displaying the XSLT files, and reindexing the data.

On at least 7 different installs now, I've had to "update systempreferences set value = "MARC21" where variable = "marcflavour";" The value was marc21, from install.

I don't see where the problem is coming from - maybe from the config file that passes "marc21" to the install script?

**Comment by MagnusEnger** [comment]
It's line [92](https://github.com/digibib/kohadevbox/blob/master/setup-koha.sh#L92):

echo "INSERT INTO systempreferences SET variable = 'marcflavour', value = '$installer_marcflavour';" | sudo koha-mysql "$instance_name"

Sounds like we have to uppercase $installer_marcflavour before we do that, then. (But as far as I can remember, we need it to be lowercase in other contexts.)

**Comment by wizzyrea** [comment]
oh, that should be easy enough to do. ^.^
