### ISSUE TITLE
config.cfg 'instance_name' of more than 11 characters will cause install to fail

### ISSUE THREAD

**Issue by bartonski** [digibib/kohadevbox#56]
Apparently usernames of more than 16 characters are not allowed. Because the string 'koha_', five characters long,  is appended to 'instance_name', this leaves 11 characters for instance_name.

==> default: ERROR 1470 (HY000) at line 2: String 'koha_barton_kohadev' is too long for user name (should be no longer than 16)

Because the user was not created, errors cascaded because the home directory for  koha_barton_kohadev was also not created.

**Comment by MagnusEnger** [comment]
There is already a Koha bug for this:

Bug 10205 - koha-create error handling
http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=10205

And an earlier version of that bug:
Bug 7428 - koha-create should check for length of instancename
http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=7428

I think actual checking of the length should be done in koha-create, but adding a warning about the max length to our config.cfg-sample is a good idea.

**Comment by bartonski** [comment]
I think that failing to create the koha instance should also be a fatal error. If koha-create has an error code, this should be checked, if not, there should be some rudimentary checking to make sure that the home directory for the instance has been created.

**Comment by MagnusEnger** [comment]
Good point! I'll open a new bug for that.

**Comment by tomascohen** [comment]
This is already handled by the provisioning scripts.
