### ISSUE TITLE
kohasite.t fails when the instance name is not 'kohaclone'

### ISSUE THREAD

**Issue by bartonski** [digibib/kohadevbox#64]
in `t/kohasite.t`, `$site_name` is hard coded to`'kohadev'`

This causes all tests to fail if the site name is *not* `kohadev`

    my $site_name = 'kohadev';
    my $site_dir = '/etc/koha/sites/' . $site_name;
    my $site_conf = $site_dir . '/koha-conf.xml';
    ...

The script `setup-koha.sh` needs to modify t/kohasite.t to  change 'kohadev' to the value of `instance_name` in `config.cfg`.

**Comment by MagnusEnger** [comment]
Hm, I'm a bit sceptical about rewriting t/kohasite.t - won't that create a (potential) conflict for future updates (git pull)? My preference would be to have the test file read the config file, I think. 

(And sorry for hardcoding things in the first place!)

**Comment by bartonski** [comment]
ah, good point about the git pull... reading from the test file shouldn't be hard either, come to think.

**Comment by tomascohen** [comment]
This test file is no longer in the source tree as ansible itself tests for success on each task it is asked to run.
