### ISSUE TITLE
"SSH command responded with a non-zero exit status"

### ISSUE THREAD

**Issue by clkirby1** [digibib/kohadevbox#67]
When I run "Vagrant Up", I have been getting the error messages above and below. 

"Failed test ['/home/vagrant/koaclone/koha_perl_deps.pl] is not executable. 

I am admittedly, very new to Linux, Vagrant, and Koha.

**Comment by wizzyrea** [comment]
Hi, 

As far as I can tell the SSH error doesn't cause a problem. I'm not sure about the Failed test one, I was unable to replicate it.

Cheers,
Liz

**Comment by tomascohen** [comment]
This is usually because the virtual machine didn't boot properly. I'm closing this bug because I cannot reproduce it.

Please read the README.md file so you don't miss any step. And fill a new issue if you find any new problem in current master.
