### ISSUE TITLE
'vagrant up' command fails

### ISSUE THREAD

**Issue by KohaAloha** [digibib/kohadevbox#71]
here's the error...

mason@sakie:~/git/kohadevbox$ vagrant plugin install vagrant-cachier
Installing the 'vagrant-cachier' plugin. This can take a few minutes...
Installed the plugin 'vagrant-cachier (1.2.1)'!

mason@sakie:~/git/kohadevbox$  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/debian-7.8' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'chef/debian-7.8'
    default: URL: https://atlas.hashicorp.com/chef/debian-7.8
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: chef/debian-7.8
Actual name: bento/debian-7.8
mason@sakie:~/git/kohadevbox$

**Comment by boutros** [comment]
Hi, Thanks for your report.
The box must have been removed by the provider (chef)
I can't remember why that particular box was chosen, do you @MagnusEnger ?
I suggest we switch to a debian/jessie box:
https://atlas.hashicorp.com/debian/boxes/jessie64

**Comment by MagnusEnger** [comment]
It seemed like a good idea at the time? ;-) Any basic, uptodate Debian box should do the trick, I think.

**Comment by boutros** [comment]
Tried width debian 8.10, but provisioning failed with:
`default: sudo: cpanm: command not found`

Should i use debian 7 still?

Have to admit that none of us at Deichman uses the kohadevbox, so I'd be happy to give commit-acces to anyone who wants to maintain it

**Comment by tomascohen** [comment]
If you take a look at the ansible branch, you will notice it support
choosing from different flavours (wheezy, jessie, trusty). It is designed
to do what is neded on each distribution.
You can grab the Wheezy box I'm using there.

2015-09-28 7:36 GMT-03:00 Petter Goksøyr Åsen <notifications@github.com>:

> Tried width debian 8.10, but provisioning failed with:
> default: sudo: cpanm: command not found
>
> Should i use debian 7 still?
>
> Have to admit that none of us at Deichman uses the kohadevbox, so I'd be
> happy to give commit-acces to anyone who wants to maintain it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digibib/kohadevbox/issues/71#issuecomment-143704119>.
>



-- 
Tomás Cohen Arazi
Theke Solutions (http://theke.io)
✆ +54 9351 3513384
GPG: B76C 6E7C 2D80 551A C765  E225 0A27 2EA1 B2F3 C15F

**Comment by boutros** [comment]
Thanks Tomas,
I tried both debian/wheezy64 and debian/jessie64 - and they result in a bunch of errors like thos reported in issue #70. Could you take a look, @MagnusEnger?

**Comment by MagnusEnger** [comment]
Hm, I seem to get a different message:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'chef/debian-7.8'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'chef/debian-7.8' is up to date...
==> default: A newer version of the box 'bento/debian-7.8' is available! You currently
==> default: have version '1.0.0'. The latest is version '2.2.1'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: kohadevbox_default_1443635453256_77484
```

**Comment by MagnusEnger** [comment]
@KohaAloha: Could you check what happens if you replace chef/debian-7.8 with bento/debian-7.8?

**Comment by WNickC** [comment]
I ran into the same issue of missing chef.
Replacing with bento worked once I added gcc to the packages to be installed

**Comment by tomascohen** [comment]
Why not sticking to debian/jessie64 or debian/wheezy64?

2015-10-13 16:37 GMT-03:00 WNickC <notifications@github.com>:

> I ran into the same issue of missing chef.
> Replacing with bento worked once I added gcc to the packages to be
> installed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digibib/kohadevbox/issues/71#issuecomment-147825992>.
>



-- 
Tomás Cohen Arazi
Theke Solutions (http://theke.io)
✆ +54 9351 3513384
GPG: B76C 6E7C 2D80 551A C765  E225 0A27 2EA1 B2F3 C15F

**Comment by WNickC** [comment]
Heh, was trying bento without looking here first so just added my comment :-)

Retried, wheezy64 runs through fine.  jessie64 won't install koha-common because of unmet dependencies:
libnet-z3950-zoom-perl
idzebra-2.0
yaz

**Comment by tomascohen** [comment]
The 'legacy' branch this issue is about has been deprecated and no longer maintained (unless someone volunteers to). Closing this issue.
