### ISSUE TITLE
"vagrant up wheezy" fails with ansible related error

### ISSUE THREAD

**Issue by kylemhall** [digibib/kohadevbox#76]
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.

I have not tried with anything besides wheezy.

**Comment by kylemhall** [comment]
Same with trusty.

**Comment by tomascohen** [comment]
What OS?

**Comment by tomascohen** [comment]
Ah, you are missing Ansible. That's it. It is missing on the README.

**Comment by kylemhall** [comment]
You are correct! Thanks!
