### ISSUE TITLE
userpermissions.sql (and possibly other tables) not filled when skip_webinstaller="1"

### ISSUE THREAD

**Issue by wizzyrea** [digibib/kohadevbox#86]
The symptom of this is the following:

"After creating a patron, when I go to "Set permissions" there are no permissions to edit. There is just a title and then "save" and "cancel" button."

The only way to recover from this seems to be drop/create a new database, and run through the webinstaller.

A guaranteed consistent work around is to vagrant destroy, set skip_webinstaller="0"  in config.cnf, and then vagrant up again.

**Comment by wizzyrea** [comment]
Of course, you then have to run through the web installer. It's better than having a subtly broken install though!

**Comment by wizzyrea** [comment]
It appears that bug 13632 is what caused this. Hopefully I'll have a pull request for you shortly. :)

**Comment by tomascohen** [comment]
@wizzyrea This is not really implemented yet on the new master branch. There's a specific issue opened for it. I hope to have it implemented ASAP, but haven't got the time yet. PRs welcome :-D
