### ISSUE TITLE
koha-shell kohadev uses package perl5lib, should use kohaclone instead

### ISSUE THREAD

**Issue by wizzyrea** [digibib/kohadevbox#88]
We need to teach the devbox to use the right PERL5LIB  for koha-shell so that when we run tests under koha-shell, they don't test against the package code instead of the git code.

**Comment by tomascohen** [comment]
Have you tried the ansible branch?

**Comment by wizzyrea** [comment]
I haven't - just solving problems for existing vagrant devbox users.

**Comment by wizzyrea** [comment]
Am I to understand that support for the vagrant one has been discontinued? If so we should probably change the readme.

**Comment by MagnusEnger** [comment]
Both branches use Vagrant. One uses Ansible to set things up, the other uses a plain shell script.

**Comment by tomascohen** [comment]
Liz, I asked only because the ansible branch -which as @MagnusEnger said implements provisioning using Ansible- already has that fixed. See here:

https://github.com/digibib/kohadevbox/blob/ansible/roles/kohadevbox/templates/instance_bashrc.j2

**Comment by wizzyrea** [comment]
It's all good, I meant the distinction between the original one with the shell script and the ansible branch. If we should be using ansible instead, and have no intentions of updating the master branch, then we should make ansible the master. Just my opinion.

**Comment by wizzyrea** [comment]
Thank you for the patch, i'll have a look.

**Comment by tomascohen** [comment]
The patch has already been pushed to the legacy branch. Closing.
