### ISSUE TITLE
ansible: ERROR: become is not a legal parameter in an Ansible Playbook

### ISSUE THREAD

**Issue by bartonski** [digibib/kohadevbox#90]
`vagrant up` leads to the following error:

    ==> jessie: Running provisioner: ansible...
        jessie: Running ansible-playbook...
    ERROR: become is not a legal parameter in an Ansible Playbook
    Ansible failed to complete successfully. Any error output should be
    visible above. Please fix these errors and try again.

**Comment by bartonski** [comment]
This turned out to be due to an outdated version of ansible on Ubuntu 14.04.

      become: True
      become_user: root

aren't available until ansible version 1.9.

**Comment by tomascohen** [comment]
I updated the README.md file to mention this requirement. @bartonski 's solution broke ansible, so looking forward for a more robust method to do this. Maybe a shell script to test for requirements, probably better pull ansible inside the VM and run the playbook directly on the VM (useful for Windows users, but haven't got any requests to spend time on that from windows users).
