### ISSUE TITLE
SKIP_WEBINSTALLER is not implemented

### ISSUE THREAD

**Issue by tomascohen** [digibib/kohadevbox#93]
We introduced the vairable injection (from ENV into ansible through Vagrant) but it hasn't been implemented. It is waiting for [https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=15392](url) so it is not so kohadevbox-specific.

**Comment by tomascohen** [comment]
HI, @wizzyrea

**Comment by bartonski** [comment]
Could we at least create the database?

**Comment by boutros** [comment]
We have implemented an automation of webinstaller, if you're interested:
https://github.com/digibib/koha-docker/tree/master/files/installer
It will take care of initial install as well as update database on upgrades.

I think it just would need some small modifications to take variables from user.yml,
like user, password, url

**Comment by tomascohen** [comment]
Now that we have [bug 10337](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=10337) this one should be pretty straightforward to implement.

**Comment by tomascohen** [comment]
Closing this one. Only Issue #2 is missing right now :-D
